//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.WindowsAPICodePack.Sensors.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedMessages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.WindowsAPICodePack.Sensors.Resources.LocalizedMessages", typeof(LocalizedMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Data field array cannot be null or empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SensorEmptyData {
            get {
                return ResourceManager.GetString("SensorEmptyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Property keys array cannot be null or empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SensorEmptyProperties {
            get {
                return ResourceManager.GetString("SensorEmptyProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sensor id=&apos;{0}&apos; type=&apos;{1}&apos; category=&apos;{2}&apos; name=&apos;{3}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SensorGetString {
            get {
                return ResourceManager.GetString("SensorGetString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sensors collection cannot be null or empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SensorManagerEmptySensorsCollection {
            get {
                return ResourceManager.GetString("SensorManagerEmptySensorsCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sensor not initialized. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SensorNotInitialized {
            get {
                return ResourceManager.GetString("SensorNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data contains a null value at index {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SensorNullValueAtIndex {
            get {
                return ResourceManager.GetString("SensorNullValueAtIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not find property. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SensorPropertyNotFound {
            get {
                return ResourceManager.GetString("SensorPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No sensors found. Are any sensor drivers installed? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SensorsNotFound {
            get {
                return ResourceManager.GetString("SensorsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to get report from sensor. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SensorUnableToGetReport {
            get {
                return ResourceManager.GetString("SensorUnableToGetReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unexpected pointer size. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SensorUnexpectedPointerSize {
            get {
                return ResourceManager.GetString("SensorUnexpectedPointerSize", resourceCulture);
            }
        }
    }
}
