//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.WindowsAPICodePack.Shell.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedMessages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.WindowsAPICodePack.Shell.Resources.LocalizedMessages", typeof(LocalizedMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   AddToMostRecentlyUsedList cannot be changed while dialog is showing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddToMostRecentlyUsedListCannotBeChanged {
            get {
                return ResourceManager.GetString("AddToMostRecentlyUsedListCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AlwaysAppendDefaultExtension cannot be changed while dialog is showing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AlwaysAppendDefaultExtensionCannotBeChanged {
            get {
                return ResourceManager.GetString("AlwaysAppendDefaultExtensionCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Index was outside the bounds of the CommonFileDialogComboBox. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ComboBoxIndexOutsideBounds {
            get {
                return ResourceManager.GetString("ComboBoxIndexOutsideBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File name not available - dialog was canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CommonFileDialogCanceled {
            get {
                return ResourceManager.GetString("CommonFileDialogCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shell item could not be created. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CommonFileDialogCannotCreateShellItem {
            get {
                return ResourceManager.GetString("CommonFileDialogCannotCreateShellItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Handle provided cannot be IntPtr.Zero. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CommonFileDialogInvalidHandle {
            get {
                return ResourceManager.GetString("CommonFileDialogInvalidHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multiple files selected - the FileNames property should be used instead. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CommonFileDialogMultipleFiles {
            get {
                return ResourceManager.GetString("CommonFileDialogMultipleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multiple files selected - the Items property should be used instead. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CommonFileDialogMultipleItems {
            get {
                return ResourceManager.GetString("CommonFileDialogMultipleItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File name not available - dialog has not closed yet. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CommonFileDialogNotClosed {
            get {
                return ResourceManager.GetString("CommonFileDialogNotClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Common File Dialog requires Windows Vista or later. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CommonFileDialogRequiresVista {
            get {
                return ResourceManager.GetString("CommonFileDialogRequiresVista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Office Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CommonFiltersOffice {
            get {
                return ResourceManager.GetString("CommonFiltersOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Picture Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CommonFiltersPicture {
            get {
                return ResourceManager.GetString("CommonFiltersPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CommonFiltersText {
            get {
                return ResourceManager.GetString("CommonFiltersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CreatePrompt cannot be changed while dialog is showing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreatePromptCannotBeChanged {
            get {
                return ResourceManager.GetString("CreatePromptCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Custom controls cannot be removed from a File dialog once added. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogControlCollectionCannotRemoveControls {
            get {
                return ResourceManager.GetString("DialogControlCollectionCannotRemoveControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Control name cannot be null or zero length. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogControlCollectionEmptyName {
            get {
                return ResourceManager.GetString("DialogControlCollectionEmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CommonFileDialogMenuItem controls can only be added to CommonFileDialogMenu controls. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogControlCollectionMenuItemControlsCannotBeAdded {
            get {
                return ResourceManager.GetString("DialogControlCollectionMenuItemControlsCannotBeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modifying controls collection while dialog is showing is not supported. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogControlCollectionModifyingControls {
            get {
                return ResourceManager.GetString("DialogControlCollectionModifyingControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dialog cannot have more than one control with the same name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogControlCollectionMoreThanOneControl {
            get {
                return ResourceManager.GetString("DialogControlCollectionMoreThanOneControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dialog control must be removed from current collections first. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogControlCollectionRemoveControlFirst {
            get {
                return ResourceManager.GetString("DialogControlCollectionRemoveControlFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EnsureFileExists cannot be changed while dialog is showing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EnsureFileExistsCannotBeChanged {
            get {
                return ResourceManager.GetString("EnsureFileExistsCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EnsurePathExists cannot be changed while dialog is showing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EnsurePathExistsCannotBeChanged {
            get {
                return ResourceManager.GetString("EnsurePathExistsCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EnsureReadOnly cannot be changed while dialog is showing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EnsureReadonlyCannotBeChanged {
            get {
                return ResourceManager.GetString("EnsureReadonlyCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EnsureValidNames cannot be changed while dialog is showing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EnsureValidNamesCannotBeChanged {
            get {
                return ResourceManager.GetString("EnsureValidNamesCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Browsing to object failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExplorerBrowserBrowseToObjectFailed {
            get {
                return ResourceManager.GetString("ExplorerBrowserBrowseToObjectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ExplorerBrowser failed to get current view. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExplorerBrowserFailedToGetView {
            get {
                return ResourceManager.GetString("ExplorerBrowserFailedToGetView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to get icon size. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExplorerBrowserIconSize {
            get {
                return ResourceManager.GetString("ExplorerBrowserIconSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unexpected error retrieving item count. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExplorerBrowserItemCount {
            get {
                return ResourceManager.GetString("ExplorerBrowserItemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unexpected error retrieving selected item count. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExplorerBrowserSelectedItemCount {
            get {
                return ResourceManager.GetString("ExplorerBrowserSelectedItemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unexpected error retrieving selection. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExplorerBrowserUnexpectedError {
            get {
                return ResourceManager.GetString("ExplorerBrowserUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unexpected error retrieving view items. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExplorerBrowserViewItems {
            get {
                return ResourceManager.GetString("ExplorerBrowserViewItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The given path does not exist ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilePathNotExist {
            get {
                return ResourceManager.GetString("FilePathNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Guid does not identify a known folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderIdsUnknownGuid {
            get {
                return ResourceManager.GetString("FolderIdsUnknownGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ControlPanel Category に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderTypeCategory {
            get {
                return ResourceManager.GetString("FolderTypeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ControlPanel Classic に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderTypeClassic {
            get {
                return ResourceManager.GetString("FolderTypeClassic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Communications に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderTypeCommunications {
            get {
                return ResourceManager.GetString("FolderTypeCommunications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compressed Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderTypeCompressedFolder {
            get {
                return ResourceManager.GetString("FolderTypeCompressedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contacts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderTypeContacts {
            get {
                return ResourceManager.GetString("FolderTypeContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Documents に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderTypeDocuments {
            get {
                return ResourceManager.GetString("FolderTypeDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Games に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderTypeGames {
            get {
                return ResourceManager.GetString("FolderTypeGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generic Library に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderTypeGenericLibrary {
            get {
                return ResourceManager.GetString("FolderTypeGenericLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderTypeInvalid {
            get {
                return ResourceManager.GetString("FolderTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Library に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderTypeLibrary {
            get {
                return ResourceManager.GetString("FolderTypeLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Music に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderTypeMusic {
            get {
                return ResourceManager.GetString("FolderTypeMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Music Icons に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderTypeMusicIcons {
            get {
                return ResourceManager.GetString("FolderTypeMusicIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Network Explorer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderTypeNetworkExplorer {
            get {
                return ResourceManager.GetString("FolderTypeNetworkExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Specified に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderTypeNotSpecified {
            get {
                return ResourceManager.GetString("FolderTypeNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderTypeOpenSearch {
            get {
                return ResourceManager.GetString("FolderTypeOpenSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other Users に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderTypeOtherUsers {
            get {
                return ResourceManager.GetString("FolderTypeOtherUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pictures に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderTypePictures {
            get {
                return ResourceManager.GetString("FolderTypePictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Printers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderTypePrinters {
            get {
                return ResourceManager.GetString("FolderTypePrinters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RecordedTV に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderTypeRecordedTV {
            get {
                return ResourceManager.GetString("FolderTypeRecordedTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RecycleBin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderTypeRecycleBin {
            get {
                return ResourceManager.GetString("FolderTypeRecycleBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saved Games に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderTypeSavedGames {
            get {
                return ResourceManager.GetString("FolderTypeSavedGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search Connector に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderTypeSearchConnector {
            get {
                return ResourceManager.GetString("FolderTypeSearchConnector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Searches に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderTypeSearches {
            get {
                return ResourceManager.GetString("FolderTypeSearches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generic SearchResults に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderTypeSearchResults {
            get {
                return ResourceManager.GetString("FolderTypeSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Software Explorer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderTypeSoftwareExplorer {
            get {
                return ResourceManager.GetString("FolderTypeSoftwareExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderTypeUserFiles {
            get {
                return ResourceManager.GetString("FolderTypeUserFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Users Libraries に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderTypeUserLibraries {
            get {
                return ResourceManager.GetString("FolderTypeUserLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Videos に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderTypeVideos {
            get {
                return ResourceManager.GetString("FolderTypeVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IsExpandedMode cannot be changed while dialog is showing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IsExpandedModeCannotBeChanged {
            get {
                return ResourceManager.GetString("IsExpandedModeCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Custom categories cannot be added while recent documents tracking is turned off. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string JumpListCustomCategoriesDisabled {
            get {
                return ResourceManager.GetString("JumpListCustomCategoriesDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file type is not registered with this application. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string JumpListFileTypeNotRegistered {
            get {
                return ResourceManager.GetString("JumpListFileTypeNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JumpListLink&apos;s path is required and cannot be null. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string JumpListLinkPathRequired {
            get {
                return ResourceManager.GetString("JumpListLinkPathRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JumpListLink&apos;s title is required and cannot be null. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string JumpListLinkTitleRequired {
            get {
                return ResourceManager.GetString("JumpListLinkTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Negative numbers are not allowed for the ordinal position. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string JumpListNegativeOrdinalPosition {
            get {
                return ResourceManager.GetString("JumpListNegativeOrdinalPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Given Known Folder ID is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KnownFolderInvalidGuid {
            get {
                return ResourceManager.GetString("KnownFolderInvalidGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parsing name is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KnownFolderParsingName {
            get {
                return ResourceManager.GetString("KnownFolderParsingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Creation of window has failed, view inner exception for details. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageListenerCannotCreateWindow {
            get {
                return ResourceManager.GetString("MessageListenerCannotCreateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window class could not be registered, check inner exception for more details. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageListenerClassNotRegistered {
            get {
                return ResourceManager.GetString("MessageListenerClassNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Message filter registration failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageListenerFilterUnableToRegister {
            get {
                return ResourceManager.GetString("MessageListenerFilterUnableToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No listener handled of that value is registered. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageListenerFilterUnknownListenerHandle {
            get {
                return ResourceManager.GetString("MessageListenerFilterUnknownListenerHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot create window on the listener thread because there is no existing window on the listener thread. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageListenerNoWindowHandle {
            get {
                return ResourceManager.GetString("MessageListenerNoWindowHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NavigateToShortcut cannot be changed while dialog is showing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NavigateToShortcutCannotBeChanged {
            get {
                return ResourceManager.GetString("NavigateToShortcutCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parent cannot be null. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NavigationLogNullParent {
            get {
                return ResourceManager.GetString("NavigationLogNullParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The method or operation is not implemented. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotImplementedException {
            get {
                return ResourceManager.GetString("NotImplementedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OverwritePrompt cannot be changed while dialog is showing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OverwritePromptCannotBeChanged {
            get {
                return ResourceManager.GetString("OverwritePromptCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This CanonicalName is not a valid index. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PropertyCollectionCanonicalInvalidIndex {
            get {
                return ResourceManager.GetString("PropertyCollectionCanonicalInvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This PropertyKey is not a valid index. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PropertyCollectionInvalidIndex {
            get {
                return ResourceManager.GetString("PropertyCollectionInvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Argument CanonicalName cannot be null or empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PropertyCollectionNullCanonicalName {
            get {
                return ResourceManager.GetString("PropertyCollectionNullCanonicalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Index was outside the bounds of the CommonFileDialogRadioButtonList. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RadioButtonListIndexOutOfBounds {
            get {
                return ResourceManager.GetString("RadioButtonListIndexOutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RestoreDirectory cannot be changed while dialog is showing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RestoreDirectoryCannotBeChanged {
            get {
                return ResourceManager.GetString("RestoreDirectoryCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retrieved a null shell item from dialog. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveFileNullItem {
            get {
                return ResourceManager.GetString("SaveFileNullItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Given property key is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SearchConditionFactoryInvalidProperty {
            get {
                return ResourceManager.GetString("SearchConditionFactoryInvalidProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shell Exception has occurred, look at inner exception for information. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellExceptionDefaultText {
            get {
                return ResourceManager.GetString("ShellExceptionDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GetParsingName has failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellHelperGetParsingNameFailed {
            get {
                return ResourceManager.GetString("ShellHelperGetParsingNameFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The given CanonicalName is not valid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellInvalidCanonicalName {
            get {
                return ResourceManager.GetString("ShellInvalidCanonicalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DefaultSaveFolder path not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellLibraryDefaultSaveFolderNotFound {
            get {
                return ResourceManager.GetString("ShellLibraryDefaultSaveFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LibraryName cannot be empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellLibraryEmptyName {
            get {
                return ResourceManager.GetString("ShellLibraryEmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder path not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellLibraryFolderNotFound {
            get {
                return ResourceManager.GetString("ShellLibraryFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid FolderType Guid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellLibraryInvalidFolderType {
            get {
                return ResourceManager.GetString("ShellLibraryInvalidFolderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The given known folder is not a valid library. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellLibraryInvalidLibrary {
            get {
                return ResourceManager.GetString("ShellLibraryInvalidLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t get the display name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellObjectCannotGetDisplayName {
            get {
                return ResourceManager.GetString("ShellObjectCannotGetDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Destination array too small, or invalid arrayIndex. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellObjectCollectionArrayTooSmall {
            get {
                return ResourceManager.GetString("ShellObjectCollectionArrayTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Must have at least one shell object in the collection. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellObjectCollectionEmptyCollection {
            get {
                return ResourceManager.GetString("ShellObjectCollectionEmptyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot insert items into a read only list. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellObjectCollectionInsertReadOnly {
            get {
                return ResourceManager.GetString("ShellObjectCollectionInsertReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot remove items from a read only list. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellObjectCollectionRemoveReadOnly {
            get {
                return ResourceManager.GetString("ShellObjectCollectionRemoveReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shell item could not be created. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellObjectCreationFailed {
            get {
                return ResourceManager.GetString("ShellObjectCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shell Object creation requires Windows Vista or higher operating system. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellObjectFactoryPlatformNotSupported {
            get {
                return ResourceManager.GetString("ShellObjectFactoryPlatformNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to Create Shell Item. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellObjectFactoryUnableToCreateItem {
            get {
                return ResourceManager.GetString("ShellObjectFactoryUnableToCreateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Registration for change notification has failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellObjectWatcherRegisterFailed {
            get {
                return ResourceManager.GetString("ShellObjectWatcherRegisterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to change watched events while listening. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellObjectWatcherUnableToChangeEvents {
            get {
                return ResourceManager.GetString("ShellObjectWatcherUnableToChangeEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The value on this property cannot be set. To set the property value, use the ShellObject that is associated with this property. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellPropertyCannotSetProperty {
            get {
                return ResourceManager.GetString("ShellPropertyCannotSetProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No constructor found matching requested argument types. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellPropertyFactoryConstructorNotFound {
            get {
                return ResourceManager.GetString("ShellPropertyFactoryConstructorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to set property. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellPropertySetValue {
            get {
                return ResourceManager.GetString("ShellPropertySetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to get writable property store for this property. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellPropertyUnableToGetWritableProperty {
            get {
                return ResourceManager.GetString("ShellPropertyUnableToGetWritableProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A value had to be truncated in a string or rounded if a numeric value. Set AllowTruncatedValue to true to prevent this exception. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellPropertyValueTruncated {
            get {
                return ResourceManager.GetString("ShellPropertyValueTruncated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This Property is available on Windows 7 only. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellPropertyWindows7 {
            get {
                return ResourceManager.GetString("ShellPropertyWindows7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This property only accepts a value of type \&quot;{0}\&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellPropertyWrongType {
            get {
                return ResourceManager.GetString("ShellPropertyWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to set list of sort columns. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellSearchFolderUnableToSetSortColumns {
            get {
                return ResourceManager.GetString("ShellSearchFolderUnableToSetSortColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to set visible columns. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellSearchFolderUnableToSetVisibleColumns {
            get {
                return ResourceManager.GetString("ShellSearchFolderUnableToSetVisibleColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CurrentSize (width or height) cannot be greater than the maximum size: {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellThumbnailCurrentSizeRange {
            get {
                return ResourceManager.GetString("ShellThumbnailCurrentSizeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The current ShellObject does not have a thumbnail. Try using ShellThumbnailFormatOption.Default to get the icon for this item. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellThumbnailDoesNotHaveThumbnail {
            get {
                return ResourceManager.GetString("ShellThumbnailDoesNotHaveThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The current ShellObject does not have a valid thumbnail handler or there was a problem in extracting the thumbnail for this specific shell object. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellThumbnailNoHandler {
            get {
                return ResourceManager.GetString("ShellThumbnailNoHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CurrentSize (width or height) cannot be 0. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellThumbnailSizeCannotBe0 {
            get {
                return ResourceManager.GetString("ShellThumbnailSizeCannotBe0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ShowHiddenItems cannot be changed while dialog is showing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShowHiddenItemsCannotBeChanged {
            get {
                return ResourceManager.GetString("ShowHiddenItemsCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show places list cannot be changed while dialog is showing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShowPlacesListCannotBeChanged {
            get {
                return ResourceManager.GetString("ShowPlacesListCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Stock Icon identifier given is invalid ({0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StockIconInvalidGuid {
            get {
                return ResourceManager.GetString("StockIconInvalidGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Child control&apos;s window handle cannot be zero. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TabbedThumbnailZeroChildHandle {
            get {
                return ResourceManager.GetString("TabbedThumbnailZeroChildHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parent window handle cannot be zero. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TabbedThumbnailZeroParentHandle {
            get {
                return ResourceManager.GetString("TabbedThumbnailZeroParentHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TabbedThumbnailProxyWindow has not been set. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TasbarWindowProxyWindowSet {
            get {
                return ResourceManager.GetString("TasbarWindowProxyWindowSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A valid active Window is needed to update the Taskbar. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TaskbarManagerValidWindowRequired {
            get {
                return ResourceManager.GetString("TaskbarManagerValidWindowRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The array of buttons must contain at least 1 item. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TaskbarWindowEmptyButtonArray {
            get {
                return ResourceManager.GetString("TaskbarWindowEmptyButtonArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tool bar buttons for this window are already added. Please refer to the Remarks section of the AddButtons method for more information on updating the properties or hiding existing buttons. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TaskbarWindowManagerButtonsAlreadyAdded {
            get {
                return ResourceManager.GetString("TaskbarWindowManagerButtonsAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value is already set. It cannot be set more than once. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TaskbarWindowValueSet {
            get {
                return ResourceManager.GetString("TaskbarWindowValueSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The given control has not been added to the taskbar. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ThumbnailManagerControlNotAdded {
            get {
                return ResourceManager.GetString("ThumbnailManagerControlNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window handle is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ThumbnailManagerInvalidHandle {
            get {
                return ResourceManager.GetString("ThumbnailManagerInvalidHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This preview has already been added. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ThumbnailManagerPreviewAdded {
            get {
                return ResourceManager.GetString("ThumbnailManagerPreviewAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The given preview has not been added to the taskbar. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ThumbnailManagerPreviewNotAdded {
            get {
                return ResourceManager.GetString("ThumbnailManagerPreviewNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maximum number of buttons allowed is 7. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ThumbnailToolbarManagerMaxButtons {
            get {
                return ResourceManager.GetString("ThumbnailToolbarManagerMaxButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Null or empty arrays are not allowed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ThumbnailToolbarManagerNullEmptyArray {
            get {
                return ResourceManager.GetString("ThumbnailToolbarManagerNullEmptyArray", resourceCulture);
            }
        }
    }
}
